"""
Prompt Doctor - Examiner Module
YOU BUILD THIS: The examiner prompt that grades student prompts.
Uses OpenRouter to call an LLM-as-judge.
"""

import json
import os
import re
from pathlib import Path
from openai import OpenAI
import streamlit as st
from dotenv import load_dotenv

# Load .env file from the project root directory
env_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=env_path)

# The core examiner system prompt - encodes ALL Day 2 principles
EXAMINER_SYSTEM_TEMPLATE = """You are the Examiner: a strict but fair prompt-engineering assessor.

You will be given:
- STUDENT_PROMPT: The prompt submitted by a student for evaluation
- LEVEL: The current challenge level (1-5)
- PRINCIPLES: The list of principles that the student's prompt must satisfy for this level
- SAMPLE_INPUT: The input that will be used to test the student's prompt
- LIVE_OUTPUT: The output generated by running the student's prompt on the sample input

Your job is to grade STUDENT_PROMPT against the principles for LEVEL {level}.

## Principles for This Level
{principles_text}

## Grading Rules (follow strictly)

1. **Role & Scope**: Judge the student prompt ONLY against the principles listed above for this level. Do NOT grade against principles from higher levels.

2. **Be Specific**: For each principle, evaluate in your own words. Reference the exact text of the student's prompt. Generic praise or vague criticism is not acceptable.

3. **Quote Weaknesses**: For every principle that FAILS, quote the exact weak phrase from the student prompt, or name exactly what is missing. For example: "The prompt says 'give me the answer' but this is vague — it doesn't specify what format the answer should be in."

4. **Coaching, Not Curing**: For each failed principle, ask EXACTLY ONE pointed question that leads the student toward the fix. NEVER write a corrected version of the prompt. NEVER provide an example fix. Diagnose only.

5. **Evidence-Based**: Use the LIVE_OUTPUT as evidence. If the output is malformed, incorrect, or missing fields, that is evidence of a principle failure.

6. **Chain of Thought**: Before outputting the verdict, reason step-by-step inside <reasoning> tags. Think about each principle, whether the prompt satisfies it, and what evidence supports your conclusion.

7. **Final Output**: After your reasoning, output ONLY a valid JSON object (no other text) with this exact schema:

{{
  "level": {level},
  "principles": [
    {{
      "name": "principle_name",
      "pass": true_or_false,
      "weakness": "exact weak phrase quoted or description of what's missing (empty string if pass is true)",
      "question": "one pointed question to guide the student (empty string if pass is true)"
    }}
  ],
  "ran_ok": true_or_false,
  "verdict": "pass" or "revise"
}}

The verdict is "pass" ONLY if EVERY principle passes. Otherwise it is "revise."

IMPORTANT: Return ONLY the JSON. No markdown fences, no extra text outside the JSON."""


def get_principles_text(level_data):
    """Format the principles for a given level as readable text."""
    principles = level_data.get("principles", [])
    lines = []
    for i, p in enumerate(principles, 1):
        lines.append(f"{i}. {p['name']}: {p['description']}")
    return "\n".join(lines)


def call_examiner(level_data, student_prompt, sample_input, live_output):
    """
    Call the examiner LLM to grade the student's prompt.
    
    Args:
        level_data: The level definition dict
        student_prompt: The prompt written by the student
        sample_input: The sample input for this level
        live_output: The output from running student_prompt on sample_input
    
    Returns:
        dict: The parsed JSON verdict from the examiner
    """
    level = level_data["level"]
    principles_text = get_principles_text(level_data)
    
    # Format the system prompt with level-specific details
    system_prompt = EXAMINER_SYSTEM_TEMPLATE.format(
        level=level,
        principles_text=principles_text
    )
    
    # Build the user message with the student's prompt and evidence
    user_message = f"""## STUDENT_PROMPT
{student_prompt}

## SAMPLE_INPUT
{sample_input}

## LIVE_OUTPUT
{live_output}

## LEVEL
{level}

## PRINCIPLES
{principles_text}

Now grade this student prompt. Remember: reason step-by-step inside <reasoning> tags, then output ONLY the JSON verdict."""

    # Get API key from session state, then .env, then secrets
    api_key = st.session_state.get("openrouter_api_key", "") or ""
    if not api_key.strip() or "your-openrouter" in api_key.lower() or api_key.strip() == "sk-or-v1-":
        api_key = os.environ.get("OPENROUTER_API_KEY", "")
    if not api_key.strip() or "your-openrouter" in api_key.lower() or api_key.strip() == "sk-or-v1-":
        try:
            api_key = st.secrets.get("OPENROUTER_API_KEY", "")
        except Exception:
            api_key = ""
    if not api_key.strip() or "your-openrouter" in api_key.lower() or api_key.strip() == "sk-or-v1-":
        raise ValueError(
            "🔑 OpenRouter API key not found or is a placeholder.\n\n"
            "**To fix:**\n"
            "1. Get your free API key at https://openrouter.ai/keys\n"
            "2. Edit the `.env` file and replace:\n"
            "   `OPENROUTER_API_KEY=your-openrouter-api-key-here`\n"
            "   with your actual key (starts with `sk-or-v1-`)\n"
            "3. **Restart the app** after saving the .env file\n\n"
            "Or type your key in the 'API Key Settings' section below the prompt editor."
        )
    
    # Initialize OpenAI client with OpenRouter base URL
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
    )
    
    # Use a capable judge model - keeping it consistent
    JUDGE_MODEL = os.environ.get("JUDGE_MODEL", "openai/gpt-4o-mini")
    
    try:
        response = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message}
            ],
            temperature=0.1,  # Low temperature for consistent grading
            max_tokens=2048,
        )
        
        content = response.choices[0].message.content.strip()
        
        # Extract reasoning if present (for logging/debugging)
        reasoning = ""
        reasoning_match = re.search(r'<reasoning>(.*?)</reasoning>', content, re.DOTALL)
        if reasoning_match:
            reasoning = reasoning_match.group(1).strip()
            # Remove reasoning tags from content before parsing JSON
            content = re.sub(r'<reasoning>.*?</reasoning>', '', content, flags=re.DOTALL).strip()
        
        # Clean up markdown fences if present
        content = re.sub(r'^```(?:json)?\s*', '', content)
        content = re.sub(r'\s*```$', '', content)
        content = content.strip()
        
        # Parse the JSON verdict
        verdict = json.loads(content)
        
        # Validate the verdict structure
        if "principles" not in verdict or "verdict" not in verdict:
            raise ValueError("Verdict missing required fields")
        
        # Attach reasoning for display
        verdict["_reasoning"] = reasoning
        
        return verdict
        
    except json.JSONDecodeError as e:
        return {
            "level": level,
            "principles": [
                {
                    "name": p["name"],
                    "pass": False,
                    "weakness": f"Examiner returned unparseable JSON: {str(e)}",
                    "question": "Check the examiner output format."
                }
                for p in level_data.get("principles", [])
            ],
            "ran_ok": False,
            "verdict": "revise",
            "_error": content if 'content' in locals() else str(e)
        }
    except Exception as e:
        return {
            "level": level,
            "principles": [
                {
                    "name": p["name"],
                    "pass": False,
                    "weakness": f"Examiner call failed: {str(e)}",
                    "question": "Check your API key and network connection."
                }
                for p in level_data.get("principles", [])
            ],
            "ran_ok": False,
            "verdict": "revise",
            "_error": str(e)
        }